// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0--rc2
// source: api/token/v1/service/service.proto

package service

import (
	context "context"
	pb "github.com/fredyzh/user_manager/api/token/v1/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenClient is the client API for Token service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenClient interface {
	// Token
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*pb.Token, error)
	VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*pb.Code, error)
	RegisterJWTSecret(ctx context.Context, in *RegisterJWTSecretRequest, opts ...grpc.CallOption) (*RegisterJWTSecretReply, error)
	IssueJWTToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenReply, error)
}

type tokenClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenClient(cc grpc.ClientConnInterface) TokenClient {
	return &tokenClient{cc}
}

func (c *tokenClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*pb.Token, error) {
	out := new(pb.Token)
	err := c.cc.Invoke(ctx, "/token.v1.service.Token/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*pb.Code, error) {
	out := new(pb.Code)
	err := c.cc.Invoke(ctx, "/token.v1.service.Token/VerifyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) RegisterJWTSecret(ctx context.Context, in *RegisterJWTSecretRequest, opts ...grpc.CallOption) (*RegisterJWTSecretReply, error) {
	out := new(RegisterJWTSecretReply)
	err := c.cc.Invoke(ctx, "/token.v1.service.Token/RegisterJWTSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) IssueJWTToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenReply, error) {
	out := new(IssueTokenReply)
	err := c.cc.Invoke(ctx, "/token.v1.service.Token/IssueJWTToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServer is the server API for Token service.
// All implementations must embed UnimplementedTokenServer
// for forward compatibility
type TokenServer interface {
	// Token
	ValidateToken(context.Context, *ValidateTokenRequest) (*pb.Token, error)
	VerifyCode(context.Context, *VerifyCodeRequest) (*pb.Code, error)
	RegisterJWTSecret(context.Context, *RegisterJWTSecretRequest) (*RegisterJWTSecretReply, error)
	IssueJWTToken(context.Context, *IssueTokenRequest) (*IssueTokenReply, error)
	mustEmbedUnimplementedTokenServer()
}

// UnimplementedTokenServer must be embedded to have forward compatible implementations.
type UnimplementedTokenServer struct {
}

func (UnimplementedTokenServer) ValidateToken(context.Context, *ValidateTokenRequest) (*pb.Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedTokenServer) VerifyCode(context.Context, *VerifyCodeRequest) (*pb.Code, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCode not implemented")
}
func (UnimplementedTokenServer) RegisterJWTSecret(context.Context, *RegisterJWTSecretRequest) (*RegisterJWTSecretReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterJWTSecret not implemented")
}
func (UnimplementedTokenServer) IssueJWTToken(context.Context, *IssueTokenRequest) (*IssueTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueJWTToken not implemented")
}
func (UnimplementedTokenServer) mustEmbedUnimplementedTokenServer() {}

// UnsafeTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServer will
// result in compilation errors.
type UnsafeTokenServer interface {
	mustEmbedUnimplementedTokenServer()
}

func RegisterTokenServer(s grpc.ServiceRegistrar, srv TokenServer) {
	s.RegisterService(&Token_ServiceDesc, srv)
}

func _Token_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.v1.service.Token/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_VerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).VerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.v1.service.Token/VerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).VerifyCode(ctx, req.(*VerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_RegisterJWTSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterJWTSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).RegisterJWTSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.v1.service.Token/RegisterJWTSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).RegisterJWTSecret(ctx, req.(*RegisterJWTSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_IssueJWTToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).IssueJWTToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.v1.service.Token/IssueJWTToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).IssueJWTToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Token_ServiceDesc is the grpc.ServiceDesc for Token service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Token_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "token.v1.service.Token",
	HandlerType: (*TokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _Token_ValidateToken_Handler,
		},
		{
			MethodName: "VerifyCode",
			Handler:    _Token_VerifyCode_Handler,
		},
		{
			MethodName: "RegisterJWTSecret",
			Handler:    _Token_RegisterJWTSecret_Handler,
		},
		{
			MethodName: "IssueJWTToken",
			Handler:    _Token_IssueJWTToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/token/v1/service/service.proto",
}
