# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_Timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmeta.proto\x12\nmeta.v1.pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n\x04Meta\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\tcreate_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tupdate_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tupdate_by\x18\x04 \x01(\t\"\'\n\x05Scope\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\tB0Z.github.com/fredyzh/user_manager/api/meta/v1/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/fredyzh/user_manager/api/meta/v1/pb'
  _globals['_META']._serialized_start=60
  _globals['_META']._serialized_end=191
  _globals['_SCOPE']._serialized_start=193
  _globals['_SCOPE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
