# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import empty_pb2 as empty__pb2
import service_pb2 as service__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/user.v1.service.User/Health',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.HealthReply.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/user.v1.service.User/GetUser',
                request_serializer=service__pb2.GetUserReq.SerializeToString,
                response_deserializer=service__pb2.GetUserReply.FromString,
                )
        self.GetUserByUsername = channel.unary_unary(
                '/user.v1.service.User/GetUserByUsername',
                request_serializer=service__pb2.GetUserByUsernameReq.SerializeToString,
                response_deserializer=service__pb2.GetUserByUsernameReply.FromString,
                )
        self.ResetUserPassword = channel.unary_unary(
                '/user.v1.service.User/ResetUserPassword',
                request_serializer=service__pb2.ResetUserPasswordReq.SerializeToString,
                response_deserializer=service__pb2.ResetUserPasswordReply.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/user.v1.service.User/CreateUser',
                request_serializer=service__pb2.CreateUserReq.SerializeToString,
                response_deserializer=service__pb2.CreateUserReply.FromString,
                )
        self.ListUser = channel.unary_unary(
                '/user.v1.service.User/ListUser',
                request_serializer=service__pb2.ListUserReq.SerializeToString,
                response_deserializer=service__pb2.ListUserReply.FromString,
                )
        self.VerifyPassword = channel.unary_unary(
                '/user.v1.service.User/VerifyPassword',
                request_serializer=service__pb2.VerifyPasswordReq.SerializeToString,
                response_deserializer=service__pb2.VerifyPasswordReply.FromString,
                )
        self.CreateAddress = channel.unary_unary(
                '/user.v1.service.User/CreateAddress',
                request_serializer=service__pb2.CreateAddressReq.SerializeToString,
                response_deserializer=service__pb2.CreateAddressReply.FromString,
                )
        self.GetUserAddress = channel.unary_unary(
                '/user.v1.service.User/GetUserAddress',
                request_serializer=service__pb2.GetAddressReq.SerializeToString,
                response_deserializer=service__pb2.GetAddressReply.FromString,
                )
        self.CreateProfile = channel.unary_unary(
                '/user.v1.service.User/CreateProfile',
                request_serializer=service__pb2.CreateProfileReq.SerializeToString,
                response_deserializer=service__pb2.CreateProfileReply.FromString,
                )
        self.GetUserProfile = channel.unary_unary(
                '/user.v1.service.User/GetUserProfile',
                request_serializer=service__pb2.GetProfileReq.SerializeToString,
                response_deserializer=service__pb2.GetProfileReply.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetUserPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=service__pb2.HealthReply.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=service__pb2.GetUserReq.FromString,
                    response_serializer=service__pb2.GetUserReply.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=service__pb2.GetUserByUsernameReq.FromString,
                    response_serializer=service__pb2.GetUserByUsernameReply.SerializeToString,
            ),
            'ResetUserPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetUserPassword,
                    request_deserializer=service__pb2.ResetUserPasswordReq.FromString,
                    response_serializer=service__pb2.ResetUserPasswordReply.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=service__pb2.CreateUserReq.FromString,
                    response_serializer=service__pb2.CreateUserReply.SerializeToString,
            ),
            'ListUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUser,
                    request_deserializer=service__pb2.ListUserReq.FromString,
                    response_serializer=service__pb2.ListUserReply.SerializeToString,
            ),
            'VerifyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPassword,
                    request_deserializer=service__pb2.VerifyPasswordReq.FromString,
                    response_serializer=service__pb2.VerifyPasswordReply.SerializeToString,
            ),
            'CreateAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAddress,
                    request_deserializer=service__pb2.CreateAddressReq.FromString,
                    response_serializer=service__pb2.CreateAddressReply.SerializeToString,
            ),
            'GetUserAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAddress,
                    request_deserializer=service__pb2.GetAddressReq.FromString,
                    response_serializer=service__pb2.GetAddressReply.SerializeToString,
            ),
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=service__pb2.CreateProfileReq.FromString,
                    response_serializer=service__pb2.CreateProfileReply.SerializeToString,
            ),
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=service__pb2.GetProfileReq.FromString,
                    response_serializer=service__pb2.GetProfileReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.service.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/Health',
            empty__pb2.Empty.SerializeToString,
            service__pb2.HealthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/GetUser',
            service__pb2.GetUserReq.SerializeToString,
            service__pb2.GetUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/GetUserByUsername',
            service__pb2.GetUserByUsernameReq.SerializeToString,
            service__pb2.GetUserByUsernameReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetUserPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/ResetUserPassword',
            service__pb2.ResetUserPasswordReq.SerializeToString,
            service__pb2.ResetUserPasswordReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/CreateUser',
            service__pb2.CreateUserReq.SerializeToString,
            service__pb2.CreateUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/ListUser',
            service__pb2.ListUserReq.SerializeToString,
            service__pb2.ListUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/VerifyPassword',
            service__pb2.VerifyPasswordReq.SerializeToString,
            service__pb2.VerifyPasswordReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/CreateAddress',
            service__pb2.CreateAddressReq.SerializeToString,
            service__pb2.CreateAddressReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/GetUserAddress',
            service__pb2.GetAddressReq.SerializeToString,
            service__pb2.GetAddressReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/CreateProfile',
            service__pb2.CreateProfileReq.SerializeToString,
            service__pb2.CreateProfileReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.service.User/GetUserProfile',
            service__pb2.GetProfileReq.SerializeToString,
            service__pb2.GetProfileReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
