// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.client.test.pb.grpc;

public interface BasicAuthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.pb.BasicAuth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#64;gotags: bson:"user_name" json:"user_name,omitempty"
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * &#64;gotags: bson:"user_name" json:"user_name,omitempty"
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * &#64;gotags: bson:"password" json:"password,omitempty"    
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * &#64;gotags: bson:"password" json:"password,omitempty"    
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
