// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.client.test.pb.grpc;

public interface CreateAddressReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.service.CreateAddressReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
