// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.client.test.pb.grpc;

public interface CreateUserReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.service.CreateUserReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>.meta.v1.pb.Scope scope = 3;</code>
   * @return Whether the scope field is set.
   */
  boolean hasScope();
  /**
   * <code>.meta.v1.pb.Scope scope = 3;</code>
   * @return The scope.
   */
  Scope getScope();
  /**
   * <code>.meta.v1.pb.Scope scope = 3;</code>
   */
  ScopeOrBuilder getScopeOrBuilder();
}
