// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.client.test.pb.grpc;

public final class GRPCUserClientTest {
  private GRPCUserClientTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_pb_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_pb_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_pb_BasicAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_pb_BasicAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_pb_Profile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_pb_Profile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_pb_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_pb_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\nuser.v1.pb\032\nmeta.proto\"\231\001\n" +
      "\004User\022\036\n\004meta\030\001 \001(\0132\020.meta.v1.pb.Meta\022)\n" +
      "\nbasic_auth\030\002 \001(\0132\025.user.v1.pb.BasicAuth" +
      "\022$\n\007profile\030\003 \001(\0132\023.user.v1.pb.Profile\022 " +
      "\n\005scope\030\004 \001(\0132\021.meta.v1.pb.Scope\"/\n\tBasi" +
      "cAuth\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(" +
      "\t\"\246\001\n\007Profile\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlas" +
      "t_name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\r\n\005phone\030\004 \001" +
      "(\t\022\014\n\004cell\030\005 \001(\t\022\"\n\006gender\030\006 \001(\0162\022.user." +
      "v1.pb.Gender\022$\n\007address\030\007 \001(\0132\023.user.v1." +
      "pb.Address\"C\n\007Address\022\016\n\006street\030\001 \001(\t\022\014\n" +
      "\004city\030\002 \001(\t\022\r\n\005state\030\003 \001(\t\022\013\n\003zip\030\004 \001(\t*" +
      "+\n\006Gender\022\013\n\007UNKNOWN\020\000\022\010\n\004MALE\020\001\022\n\n\006FEMA" +
      "LE\020\002B\034\n\004grpcB\022GRPCUserClientTestP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCMetaClientTest.getDescriptor(),
        });
    internal_static_user_v1_pb_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_v1_pb_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_pb_User_descriptor,
        new java.lang.String[] { "Meta", "BasicAuth", "Profile", "Scope", });
    internal_static_user_v1_pb_BasicAuth_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_v1_pb_BasicAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_pb_BasicAuth_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_user_v1_pb_Profile_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_v1_pb_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_pb_Profile_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Phone", "Cell", "Gender", "Address", });
    internal_static_user_v1_pb_Address_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_v1_pb_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_pb_Address_descriptor,
        new java.lang.String[] { "Street", "City", "State", "Zip", });
    GRPCMetaClientTest.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
