// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.client.test.pb.grpc;

public final class GRPCUserServiceClientTest {
  private GRPCUserServiceClientTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetUserReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetUserReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetUserReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetUserByUsernameReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetUserByUsernameReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetUserByUsernameReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetUserByUsernameReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_CreateUserReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_CreateUserReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_CreateUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_CreateUserReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_ListUserReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_ListUserReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_ListUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_ListUserReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_VerifyPasswordReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_VerifyPasswordReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_VerifyPasswordReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_VerifyPasswordReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_CreateProfileReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_CreateProfileReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_CreateProfileReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_CreateProfileReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetProfileReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetProfileReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetProfileReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetProfileReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_CreateAddressReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_CreateAddressReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_CreateAddressReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_CreateAddressReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetAddressReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetAddressReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_GetAddressReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_GetAddressReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_ResetUserPasswordReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_ResetUserPasswordReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_ResetUserPasswordReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_ResetUserPasswordReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_v1_service_HealthReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_v1_service_HealthReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\017user.v1.service\032\021annota" +
      "tions.proto\032\033google/protobuf/Empty.proto" +
      "\032\nuser.proto\032\nmeta.proto\"\030\n\nGetUserReq\022\n" +
      "\n\002id\030\001 \001(\t\":\n\014GetUserReply\022\n\n\002id\030\001 \001(\003\022\036" +
      "\n\004user\030\002 \001(\0132\020.user.v1.pb.User\"(\n\024GetUse" +
      "rByUsernameReq\022\020\n\010username\030\001 \001(\t\"D\n\026GetU" +
      "serByUsernameReply\022\n\n\002id\030\001 \001(\003\022\036\n\004user\030\002" +
      " \001(\0132\020.user.v1.pb.User\"U\n\rCreateUserReq\022" +
      "\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022 \n\005s" +
      "cope\030\003 \001(\0132\021.meta.v1.pb.Scope\"\035\n\017CreateU" +
      "serReply\022\n\n\002id\030\001 \001(\003\"\r\n\013ListUserReq\">\n\rL" +
      "istUserReply\022\n\n\002id\030\001 \001(\003\022!\n\007results\030\002 \003(" +
      "\0132\020.user.v1.pb.User\"Y\n\021VerifyPasswordReq" +
      "\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022 \n\005" +
      "scope\030\003 \001(\0132\021.meta.v1.pb.Scope\"-\n\023Verify" +
      "PasswordReply\022\n\n\002id\030\001 \001(\003\022\n\n\002ok\030\002 \001(\010\"D\n" +
      "\020CreateProfileReq\022\n\n\002id\030\001 \001(\t\022$\n\007profile" +
      "\030\002 \001(\0132\023.user.v1.pb.Profile\" \n\022CreatePro" +
      "fileReply\022\n\n\002id\030\001 \001(\003\"\033\n\rGetProfileReq\022\n" +
      "\n\002id\030\001 \001(\t\"C\n\017GetProfileReply\022\n\n\002id\030\001 \001(" +
      "\003\022$\n\007profile\030\002 \001(\0132\023.user.v1.pb.Profile\"" +
      "D\n\020CreateAddressReq\022\n\n\002id\030\001 \001(\t\022$\n\007addre" +
      "ss\030\002 \001(\0132\023.user.v1.pb.Address\" \n\022CreateA" +
      "ddressReply\022\n\n\002id\030\001 \001(\003\"\033\n\rGetAddressReq" +
      "\022\n\n\002id\030\001 \001(\t\"C\n\017GetAddressReply\022\n\n\002id\030\001 " +
      "\001(\003\022$\n\007address\030\002 \001(\0132\023.user.v1.pb.Addres" +
      "s\"N\n\024ResetUserPasswordReq\022\n\n\002id\030\001 \001(\t\022\024\n" +
      "\014new_password\030\002 \001(\t\022\024\n\014old_password\030\003 \001(" +
      "\t\"$\n\026ResetUserPasswordReply\022\n\n\002id\030\001 \001(\003\"" +
      "\031\n\013HealthReply\022\n\n\002ok\030\001 \001(\0102\201\013\n\004User\022_\n\006H" +
      "ealth\022\026.google.protobuf.Empty\032\034.user.v1." +
      "service.HealthReply\"\037\202\323\344\223\002\031\022\027/user/v1/se" +
      "rvice/health\022l\n\007GetUser\022\033.user.v1.servic" +
      "e.GetUserReq\032\035.user.v1.service.GetUserRe" +
      "ply\"%\202\323\344\223\002\037\022\035/user/v1/service/getuser/{i" +
      "d}\022\226\001\n\021GetUserByUsername\022%.user.v1.servi" +
      "ce.GetUserByUsernameReq\032\'.user.v1.servic" +
      "e.GetUserByUsernameReply\"1\202\323\344\223\002+\022)/user/" +
      "v1/service/getuserbyname/{username}\022\222\001\n\021" +
      "ResetUserPassword\022%.user.v1.service.Rese" +
      "tUserPasswordReq\032\'.user.v1.service.Reset" +
      "UserPasswordReply\"-\202\323\344\223\002\'\"\"/user/v1/serv" +
      "ice/resetuserpassword:\001*\022v\n\nCreateUser\022\036" +
      ".user.v1.service.CreateUserReq\032 .user.v1" +
      ".service.CreateUserReply\"&\202\323\344\223\002 \"\033/user/" +
      "v1/service/createuser:\001*\022k\n\010ListUser\022\034.u" +
      "ser.v1.service.ListUserReq\032\036.user.v1.ser" +
      "vice.ListUserReply\"!\202\323\344\223\002\033\022\031/user/v1/ser" +
      "vice/listuser\022\206\001\n\016VerifyPassword\022\".user." +
      "v1.service.VerifyPasswordReq\032$.user.v1.s" +
      "ervice.VerifyPasswordReply\"*\202\323\344\223\002$\"\037/use" +
      "r/v1/service/verifypassword:\001*\022\202\001\n\rCreat" +
      "eAddress\022!.user.v1.service.CreateAddress" +
      "Req\032#.user.v1.service.CreateAddressReply" +
      "\")\202\323\344\223\002#\"\036/user/v1/service/createaddress" +
      ":\001*\022\200\001\n\016GetUserAddress\022\036.user.v1.service" +
      ".GetAddressReq\032 .user.v1.service.GetAddr" +
      "essReply\",\202\323\344\223\002&\022$/user/v1/service/getus" +
      "eraddress/{id}\022\202\001\n\rCreateProfile\022!.user." +
      "v1.service.CreateProfileReq\032#.user.v1.se" +
      "rvice.CreateProfileReply\")\202\323\344\223\002#\"\036/user/" +
      "v1/service/createprofile:\001*\022\200\001\n\016GetUserP" +
      "rofile\022\036.user.v1.service.GetProfileReq\032 " +
      ".user.v1.service.GetProfileReply\",\202\323\344\223\002&" +
      "\022$/user/v1/service/getuserprofile/{id}B#" +
      "\n\004grpcB\031GRPCUserServiceClientTestP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          GRPCUserClientTest.getDescriptor(),
          GRPCMetaClientTest.getDescriptor(),
        });
    internal_static_user_v1_service_GetUserReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_v1_service_GetUserReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetUserReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_v1_service_GetUserReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_v1_service_GetUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetUserReply_descriptor,
        new java.lang.String[] { "Id", "User", });
    internal_static_user_v1_service_GetUserByUsernameReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_v1_service_GetUserByUsernameReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetUserByUsernameReq_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_user_v1_service_GetUserByUsernameReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_v1_service_GetUserByUsernameReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetUserByUsernameReply_descriptor,
        new java.lang.String[] { "Id", "User", });
    internal_static_user_v1_service_CreateUserReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_user_v1_service_CreateUserReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_CreateUserReq_descriptor,
        new java.lang.String[] { "Username", "Password", "Scope", });
    internal_static_user_v1_service_CreateUserReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_user_v1_service_CreateUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_CreateUserReply_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_v1_service_ListUserReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_user_v1_service_ListUserReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_ListUserReq_descriptor,
        new java.lang.String[] { });
    internal_static_user_v1_service_ListUserReply_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_user_v1_service_ListUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_ListUserReply_descriptor,
        new java.lang.String[] { "Id", "Results", });
    internal_static_user_v1_service_VerifyPasswordReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_user_v1_service_VerifyPasswordReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_VerifyPasswordReq_descriptor,
        new java.lang.String[] { "Username", "Password", "Scope", });
    internal_static_user_v1_service_VerifyPasswordReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_user_v1_service_VerifyPasswordReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_VerifyPasswordReply_descriptor,
        new java.lang.String[] { "Id", "Ok", });
    internal_static_user_v1_service_CreateProfileReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_user_v1_service_CreateProfileReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_CreateProfileReq_descriptor,
        new java.lang.String[] { "Id", "Profile", });
    internal_static_user_v1_service_CreateProfileReply_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_user_v1_service_CreateProfileReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_CreateProfileReply_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_v1_service_GetProfileReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_user_v1_service_GetProfileReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetProfileReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_v1_service_GetProfileReply_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_user_v1_service_GetProfileReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetProfileReply_descriptor,
        new java.lang.String[] { "Id", "Profile", });
    internal_static_user_v1_service_CreateAddressReq_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_user_v1_service_CreateAddressReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_CreateAddressReq_descriptor,
        new java.lang.String[] { "Id", "Address", });
    internal_static_user_v1_service_CreateAddressReply_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_user_v1_service_CreateAddressReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_CreateAddressReply_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_v1_service_GetAddressReq_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_user_v1_service_GetAddressReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetAddressReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_v1_service_GetAddressReply_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_user_v1_service_GetAddressReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_GetAddressReply_descriptor,
        new java.lang.String[] { "Id", "Address", });
    internal_static_user_v1_service_ResetUserPasswordReq_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_user_v1_service_ResetUserPasswordReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_ResetUserPasswordReq_descriptor,
        new java.lang.String[] { "Id", "NewPassword", "OldPassword", });
    internal_static_user_v1_service_ResetUserPasswordReply_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_user_v1_service_ResetUserPasswordReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_ResetUserPasswordReply_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_v1_service_HealthReply_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_user_v1_service_HealthReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_v1_service_HealthReply_descriptor,
        new java.lang.String[] { "Ok", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    GRPCUserClientTest.getDescriptor();
    GRPCMetaClientTest.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
