// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.client.test.pb.grpc;

public interface ListUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.service.ListUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>repeated .user.v1.pb.User results = 2;</code>
   */
  java.util.List<User> 
      getResultsList();
  /**
   * <code>repeated .user.v1.pb.User results = 2;</code>
   */
  User getResults(int index);
  /**
   * <code>repeated .user.v1.pb.User results = 2;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .user.v1.pb.User results = 2;</code>
   */
  java.util.List<? extends UserOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .user.v1.pb.User results = 2;</code>
   */
  UserOrBuilder getResultsOrBuilder(
      int index);
}
