// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.client.test.pb.grpc;

public interface ProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.pb.Profile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#64;gotags: bson:"first_name" json:"first_name,omitempty"  
   * </pre>
   *
   * <code>string first_name = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <pre>
   * &#64;gotags: bson:"first_name" json:"first_name,omitempty"  
   * </pre>
   *
   * <code>string first_name = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <pre>
   * &#64;gotags: bson:"last_name" json:"last_name,omitempty"  
   * </pre>
   *
   * <code>string last_name = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <pre>
   * &#64;gotags: bson:"last_name" json:"last_name,omitempty"  
   * </pre>
   *
   * <code>string last_name = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <pre>
   * &#64;gotags: bson:"email" json:"email,omitempty"  
   * </pre>
   *
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * &#64;gotags: bson:"email" json:"email,omitempty"  
   * </pre>
   *
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * &#64;gotags: bson:"phone" json:"phone,omitempty"  
   * </pre>
   *
   * <code>string phone = 4;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <pre>
   * &#64;gotags: bson:"phone" json:"phone,omitempty"  
   * </pre>
   *
   * <code>string phone = 4;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <pre>
   * &#64;gotags: bson:"cell" json:"cell,omitempty"  
   * </pre>
   *
   * <code>string cell = 5;</code>
   * @return The cell.
   */
  java.lang.String getCell();
  /**
   * <pre>
   * &#64;gotags: bson:"cell" json:"cell,omitempty"  
   * </pre>
   *
   * <code>string cell = 5;</code>
   * @return The bytes for cell.
   */
  com.google.protobuf.ByteString
      getCellBytes();

  /**
   * <pre>
   * &#64;gotags: bson:"gender" json:"gender,omitempty"  
   * </pre>
   *
   * <code>.user.v1.pb.Gender gender = 6;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <pre>
   * &#64;gotags: bson:"gender" json:"gender,omitempty"  
   * </pre>
   *
   * <code>.user.v1.pb.Gender gender = 6;</code>
   * @return The gender.
   */
  Gender getGender();

  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"address,omitempty" 
   * </pre>
   *
   * <code>.user.v1.pb.Address address = 7;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"address,omitempty" 
   * </pre>
   *
   * <code>.user.v1.pb.Address address = 7;</code>
   * @return The address.
   */
  Address getAddress();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"address,omitempty" 
   * </pre>
   *
   * <code>.user.v1.pb.Address address = 7;</code>
   */
  AddressOrBuilder getAddressOrBuilder();
}
