// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.client.test.pb.grpc;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.pb.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"meta"
   * </pre>
   *
   * <code>.meta.v1.pb.Meta meta = 1;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"meta"
   * </pre>
   *
   * <code>.meta.v1.pb.Meta meta = 1;</code>
   * @return The meta.
   */
  Meta getMeta();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"meta"
   * </pre>
   *
   * <code>.meta.v1.pb.Meta meta = 1;</code>
   */
  MetaOrBuilder getMetaOrBuilder();

  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"basic_auth"
   * </pre>
   *
   * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
   * @return Whether the basicAuth field is set.
   */
  boolean hasBasicAuth();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"basic_auth"
   * </pre>
   *
   * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
   * @return The basicAuth.
   */
  BasicAuth getBasicAuth();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"basic_auth"
   * </pre>
   *
   * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
   */
  BasicAuthOrBuilder getBasicAuthOrBuilder();

  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"profile"
   * </pre>
   *
   * <code>.user.v1.pb.Profile profile = 3;</code>
   * @return Whether the profile field is set.
   */
  boolean hasProfile();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"profile"
   * </pre>
   *
   * <code>.user.v1.pb.Profile profile = 3;</code>
   * @return The profile.
   */
  Profile getProfile();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"profile"
   * </pre>
   *
   * <code>.user.v1.pb.Profile profile = 3;</code>
   */
  ProfileOrBuilder getProfileOrBuilder();

  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"scope,omitempty"  
   * </pre>
   *
   * <code>.meta.v1.pb.Scope scope = 4;</code>
   * @return Whether the scope field is set.
   */
  boolean hasScope();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"scope,omitempty"  
   * </pre>
   *
   * <code>.meta.v1.pb.Scope scope = 4;</code>
   * @return The scope.
   */
  Scope getScope();
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"scope,omitempty"  
   * </pre>
   *
   * <code>.meta.v1.pb.Scope scope = 4;</code>
   */
  ScopeOrBuilder getScopeOrBuilder();
}
