// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.client.test.pb.grpc;

/**
 * Protobuf type {@code user.v1.pb.User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.v1.pb.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GRPCUserClientTest.internal_static_user_v1_pb_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GRPCUserClientTest.internal_static_user_v1_pb_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            User.class, User.Builder.class);
  }

  private int bitField0_;
  public static final int META_FIELD_NUMBER = 1;
  private Meta meta_;
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"meta"
   * </pre>
   *
   * <code>.meta.v1.pb.Meta meta = 1;</code>
   * @return Whether the meta field is set.
   */
  @java.lang.Override
  public boolean hasMeta() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"meta"
   * </pre>
   *
   * <code>.meta.v1.pb.Meta meta = 1;</code>
   * @return The meta.
   */
  @java.lang.Override
  public Meta getMeta() {
    return meta_ == null ? Meta.getDefaultInstance() : meta_;
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"meta"
   * </pre>
   *
   * <code>.meta.v1.pb.Meta meta = 1;</code>
   */
  @java.lang.Override
  public MetaOrBuilder getMetaOrBuilder() {
    return meta_ == null ? Meta.getDefaultInstance() : meta_;
  }

  public static final int BASIC_AUTH_FIELD_NUMBER = 2;
  private BasicAuth basicAuth_;
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"basic_auth"
   * </pre>
   *
   * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
   * @return Whether the basicAuth field is set.
   */
  @java.lang.Override
  public boolean hasBasicAuth() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"basic_auth"
   * </pre>
   *
   * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
   * @return The basicAuth.
   */
  @java.lang.Override
  public BasicAuth getBasicAuth() {
    return basicAuth_ == null ? BasicAuth.getDefaultInstance() : basicAuth_;
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"basic_auth"
   * </pre>
   *
   * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
   */
  @java.lang.Override
  public BasicAuthOrBuilder getBasicAuthOrBuilder() {
    return basicAuth_ == null ? BasicAuth.getDefaultInstance() : basicAuth_;
  }

  public static final int PROFILE_FIELD_NUMBER = 3;
  private Profile profile_;
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"profile"
   * </pre>
   *
   * <code>.user.v1.pb.Profile profile = 3;</code>
   * @return Whether the profile field is set.
   */
  @java.lang.Override
  public boolean hasProfile() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"profile"
   * </pre>
   *
   * <code>.user.v1.pb.Profile profile = 3;</code>
   * @return The profile.
   */
  @java.lang.Override
  public Profile getProfile() {
    return profile_ == null ? Profile.getDefaultInstance() : profile_;
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"profile"
   * </pre>
   *
   * <code>.user.v1.pb.Profile profile = 3;</code>
   */
  @java.lang.Override
  public ProfileOrBuilder getProfileOrBuilder() {
    return profile_ == null ? Profile.getDefaultInstance() : profile_;
  }

  public static final int SCOPE_FIELD_NUMBER = 4;
  private Scope scope_;
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"scope,omitempty"  
   * </pre>
   *
   * <code>.meta.v1.pb.Scope scope = 4;</code>
   * @return Whether the scope field is set.
   */
  @java.lang.Override
  public boolean hasScope() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"scope,omitempty"  
   * </pre>
   *
   * <code>.meta.v1.pb.Scope scope = 4;</code>
   * @return The scope.
   */
  @java.lang.Override
  public Scope getScope() {
    return scope_ == null ? Scope.getDefaultInstance() : scope_;
  }
  /**
   * <pre>
   * &#64;gotags: bson:", inline" json:"scope,omitempty"  
   * </pre>
   *
   * <code>.meta.v1.pb.Scope scope = 4;</code>
   */
  @java.lang.Override
  public ScopeOrBuilder getScopeOrBuilder() {
    return scope_ == null ? Scope.getDefaultInstance() : scope_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMeta());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getBasicAuth());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getProfile());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getScope());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMeta());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBasicAuth());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getProfile());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getScope());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof User)) {
      return super.equals(obj);
    }
    User other = (User) obj;

    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (hasBasicAuth() != other.hasBasicAuth()) return false;
    if (hasBasicAuth()) {
      if (!getBasicAuth()
          .equals(other.getBasicAuth())) return false;
    }
    if (hasProfile() != other.hasProfile()) return false;
    if (hasProfile()) {
      if (!getProfile()
          .equals(other.getProfile())) return false;
    }
    if (hasScope() != other.hasScope()) return false;
    if (hasScope()) {
      if (!getScope()
          .equals(other.getScope())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    if (hasBasicAuth()) {
      hash = (37 * hash) + BASIC_AUTH_FIELD_NUMBER;
      hash = (53 * hash) + getBasicAuth().hashCode();
    }
    if (hasProfile()) {
      hash = (37 * hash) + PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getProfile().hashCode();
    }
    if (hasScope()) {
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + getScope().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.v1.pb.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.v1.pb.User)
      UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCUserClientTest.internal_static_user_v1_pb_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCUserClientTest.internal_static_user_v1_pb_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              User.class, User.Builder.class);
    }

    // Construct using User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetaFieldBuilder();
        getBasicAuthFieldBuilder();
        getProfileFieldBuilder();
        getScopeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      basicAuth_ = null;
      if (basicAuthBuilder_ != null) {
        basicAuthBuilder_.dispose();
        basicAuthBuilder_ = null;
      }
      profile_ = null;
      if (profileBuilder_ != null) {
        profileBuilder_.dispose();
        profileBuilder_ = null;
      }
      scope_ = null;
      if (scopeBuilder_ != null) {
        scopeBuilder_.dispose();
        scopeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GRPCUserClientTest.internal_static_user_v1_pb_User_descriptor;
    }

    @java.lang.Override
    public User getDefaultInstanceForType() {
      return User.getDefaultInstance();
    }

    @java.lang.Override
    public User build() {
      User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public User buildPartial() {
      User result = new User(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(User result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.meta_ = metaBuilder_ == null
            ? meta_
            : metaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.basicAuth_ = basicAuthBuilder_ == null
            ? basicAuth_
            : basicAuthBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.profile_ = profileBuilder_ == null
            ? profile_
            : profileBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.scope_ = scopeBuilder_ == null
            ? scope_
            : scopeBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof User) {
        return mergeFrom((User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(User other) {
      if (other == User.getDefaultInstance()) return this;
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      if (other.hasBasicAuth()) {
        mergeBasicAuth(other.getBasicAuth());
      }
      if (other.hasProfile()) {
        mergeProfile(other.getProfile());
      }
      if (other.hasScope()) {
        mergeScope(other.getScope());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMetaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getBasicAuthFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getProfileFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getScopeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Meta meta_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Meta, Meta.Builder, MetaOrBuilder> metaBuilder_;
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     * @return The meta.
     */
    public Meta getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? Meta.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     */
    public Builder setMeta(Meta value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
      } else {
        metaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     */
    public Builder setMeta(
        Meta.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     */
    public Builder mergeMeta(Meta value) {
      if (metaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          meta_ != null &&
          meta_ != Meta.getDefaultInstance()) {
          getMetaBuilder().mergeFrom(value);
        } else {
          meta_ = value;
        }
      } else {
        metaBuilder_.mergeFrom(value);
      }
      if (meta_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     */
    public Builder clearMeta() {
      bitField0_ = (bitField0_ & ~0x00000001);
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     */
    public Meta.Builder getMetaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     */
    public MetaOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            Meta.getDefaultInstance() : meta_;
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"meta"
     * </pre>
     *
     * <code>.meta.v1.pb.Meta meta = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Meta, Meta.Builder, MetaOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Meta, Meta.Builder, MetaOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }

    private BasicAuth basicAuth_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BasicAuth, BasicAuth.Builder, BasicAuthOrBuilder> basicAuthBuilder_;
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     * @return Whether the basicAuth field is set.
     */
    public boolean hasBasicAuth() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     * @return The basicAuth.
     */
    public BasicAuth getBasicAuth() {
      if (basicAuthBuilder_ == null) {
        return basicAuth_ == null ? BasicAuth.getDefaultInstance() : basicAuth_;
      } else {
        return basicAuthBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     */
    public Builder setBasicAuth(BasicAuth value) {
      if (basicAuthBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        basicAuth_ = value;
      } else {
        basicAuthBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     */
    public Builder setBasicAuth(
        BasicAuth.Builder builderForValue) {
      if (basicAuthBuilder_ == null) {
        basicAuth_ = builderForValue.build();
      } else {
        basicAuthBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     */
    public Builder mergeBasicAuth(BasicAuth value) {
      if (basicAuthBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          basicAuth_ != null &&
          basicAuth_ != BasicAuth.getDefaultInstance()) {
          getBasicAuthBuilder().mergeFrom(value);
        } else {
          basicAuth_ = value;
        }
      } else {
        basicAuthBuilder_.mergeFrom(value);
      }
      if (basicAuth_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     */
    public Builder clearBasicAuth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      basicAuth_ = null;
      if (basicAuthBuilder_ != null) {
        basicAuthBuilder_.dispose();
        basicAuthBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     */
    public BasicAuth.Builder getBasicAuthBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getBasicAuthFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     */
    public BasicAuthOrBuilder getBasicAuthOrBuilder() {
      if (basicAuthBuilder_ != null) {
        return basicAuthBuilder_.getMessageOrBuilder();
      } else {
        return basicAuth_ == null ?
            BasicAuth.getDefaultInstance() : basicAuth_;
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"basic_auth"
     * </pre>
     *
     * <code>.user.v1.pb.BasicAuth basic_auth = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BasicAuth, BasicAuth.Builder, BasicAuthOrBuilder> 
        getBasicAuthFieldBuilder() {
      if (basicAuthBuilder_ == null) {
        basicAuthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BasicAuth, BasicAuth.Builder, BasicAuthOrBuilder>(
                getBasicAuth(),
                getParentForChildren(),
                isClean());
        basicAuth_ = null;
      }
      return basicAuthBuilder_;
    }

    private Profile profile_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Profile, Profile.Builder, ProfileOrBuilder> profileBuilder_;
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     * @return Whether the profile field is set.
     */
    public boolean hasProfile() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     * @return The profile.
     */
    public Profile getProfile() {
      if (profileBuilder_ == null) {
        return profile_ == null ? Profile.getDefaultInstance() : profile_;
      } else {
        return profileBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     */
    public Builder setProfile(Profile value) {
      if (profileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        profile_ = value;
      } else {
        profileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     */
    public Builder setProfile(
        Profile.Builder builderForValue) {
      if (profileBuilder_ == null) {
        profile_ = builderForValue.build();
      } else {
        profileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     */
    public Builder mergeProfile(Profile value) {
      if (profileBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          profile_ != null &&
          profile_ != Profile.getDefaultInstance()) {
          getProfileBuilder().mergeFrom(value);
        } else {
          profile_ = value;
        }
      } else {
        profileBuilder_.mergeFrom(value);
      }
      if (profile_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     */
    public Builder clearProfile() {
      bitField0_ = (bitField0_ & ~0x00000004);
      profile_ = null;
      if (profileBuilder_ != null) {
        profileBuilder_.dispose();
        profileBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     */
    public Profile.Builder getProfileBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getProfileFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     */
    public ProfileOrBuilder getProfileOrBuilder() {
      if (profileBuilder_ != null) {
        return profileBuilder_.getMessageOrBuilder();
      } else {
        return profile_ == null ?
            Profile.getDefaultInstance() : profile_;
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"profile"
     * </pre>
     *
     * <code>.user.v1.pb.Profile profile = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Profile, Profile.Builder, ProfileOrBuilder> 
        getProfileFieldBuilder() {
      if (profileBuilder_ == null) {
        profileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Profile, Profile.Builder, ProfileOrBuilder>(
                getProfile(),
                getParentForChildren(),
                isClean());
        profile_ = null;
      }
      return profileBuilder_;
    }

    private Scope scope_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Scope, Scope.Builder, ScopeOrBuilder> scopeBuilder_;
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     * @return Whether the scope field is set.
     */
    public boolean hasScope() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     * @return The scope.
     */
    public Scope getScope() {
      if (scopeBuilder_ == null) {
        return scope_ == null ? Scope.getDefaultInstance() : scope_;
      } else {
        return scopeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     */
    public Builder setScope(Scope value) {
      if (scopeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scope_ = value;
      } else {
        scopeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     */
    public Builder setScope(
        Scope.Builder builderForValue) {
      if (scopeBuilder_ == null) {
        scope_ = builderForValue.build();
      } else {
        scopeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     */
    public Builder mergeScope(Scope value) {
      if (scopeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          scope_ != null &&
          scope_ != Scope.getDefaultInstance()) {
          getScopeBuilder().mergeFrom(value);
        } else {
          scope_ = value;
        }
      } else {
        scopeBuilder_.mergeFrom(value);
      }
      if (scope_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     */
    public Builder clearScope() {
      bitField0_ = (bitField0_ & ~0x00000008);
      scope_ = null;
      if (scopeBuilder_ != null) {
        scopeBuilder_.dispose();
        scopeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     */
    public Scope.Builder getScopeBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getScopeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     */
    public ScopeOrBuilder getScopeOrBuilder() {
      if (scopeBuilder_ != null) {
        return scopeBuilder_.getMessageOrBuilder();
      } else {
        return scope_ == null ?
            Scope.getDefaultInstance() : scope_;
      }
    }
    /**
     * <pre>
     * &#64;gotags: bson:", inline" json:"scope,omitempty"  
     * </pre>
     *
     * <code>.meta.v1.pb.Scope scope = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Scope, Scope.Builder, ScopeOrBuilder> 
        getScopeFieldBuilder() {
      if (scopeBuilder_ == null) {
        scopeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Scope, Scope.Builder, ScopeOrBuilder>(
                getScope(),
                getParentForChildren(),
                isClean());
        scope_ = null;
      }
      return scopeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:user.v1.pb.User)
  }

  // @@protoc_insertion_point(class_scope:user.v1.pb.User)
  private static final User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new User();
  }

  public static User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

